project:
  type: website

website:
  title: "BUS 320 blog"
  navbar:
    right:
      - about.qmd
      - icon: mailbox
        href: mailto: example@sonoma.edu
      - icon: linkedin
        href: https://www.linkedin.com/in/example/
format:
  html:
    theme: cosmo
    css: styles.css



